#!/usr/bin/env python3
"""
Credentials Server Setup
Generates API key, creates venv, installs dependencies, and creates LaunchAgent.
"""

import os
import sys
import secrets
import subprocess
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
CREDENTIALS_SERVER = SCRIPT_DIR / "credentials_server.py"
VENV_DIR = SCRIPT_DIR / "venv"
PLIST_PATH = Path.home() / "Library/LaunchAgents/com.bios.credentials-server.plist"

API_KEY = secrets.token_urlsafe(32)


def run(cmd, check=True):
    """Run a command, print output."""
    print(f"Running: {' '.join(cmd[:3])}...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.stdout:
        print(result.stdout.strip())
    if result.returncode != 0 and check:
        print(f"ERROR: {result.stderr.strip()}")
        return False
    return True


def check_azure_auth():
    """Check if Azure CLI is authenticated."""
    print("\n=== Checking Azure Authentication ===")
    result = subprocess.run(["az", "account", "show"], capture_output=True, text=True)
    if result.returncode == 0:
        import json

        info = json.loads(result.stdout)
        print(f"✓ Logged in as: {info.get('user', {}).get('name', 'unknown')}")
        print(f"  Subscription: {info.get('name', 'unknown')}")
        return True
    else:
        print("✗ Not logged in to Azure")
        print("  Run: az login --tenant cace3155-c33d-4869-b243-25daf1604ebb")
        return False


def main():
    print("=" * 60)
    print("Azure Credentials Server Setup")
    print("=" * 60)

    if not check_azure_auth():
        print("\nFix Azure authentication first, then re-run this script.")
        sys.exit(1)

    print("\n=== Creating Virtual Environment ===")
    if VENV_DIR.exists():
        print(f"Removing old venv...")
        import shutil

        shutil.rmtree(VENV_DIR)

    if not run(["python3", "-m", "venv", str(VENV_DIR)]):
        sys.exit(1)

    print("\n=== Installing Dependencies ===")
    pip = VENV_DIR / "bin" / "pip"
    if not run([str(pip), "install", "-q", "fastapi", "uvicorn", "httpx", "pydantic"]):
        sys.exit(1)

    print("\n=== Generating API Key ===")
    print(f"API Key: {API_KEY}")
    print("⚠️  Save this key! You'll need it to access secrets.")
    print("")

    print("\n=== Creating LaunchAgent ===")
    PLIST_DIR = Path.home() / "Library/LaunchAgents"
    PLIST_DIR.mkdir(exist_ok=True)

    az_tenant = os.getenv("AZURE_TENANT_ID", "cace3155-c33d-4869-b243-25daf1604ebb")
    az_client = os.getenv("AZURE_CLIENT_ID", "1b04765e-4482-467c-b799-ee6251542ffe")
    az_secret_name = os.getenv(
        "AZURE_CLIENT_SECRET_NAME", "github-mcp-koyeb-app-client-secret"
    )

    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.bios.credentials-server</string>
    
    <key>ProgramArguments</key>
    <array>
        <string>{VENV_DIR}/bin/python</string>
        <string>{CREDENTIALS_SERVER}</string>
    </array>
    
    <key>EnvironmentVariables</key>
    <dict>
        <key>CREDENTIALS_API_KEY</key>
        <string>{API_KEY}</string>
        <key>CREDENTIALS_PORT</key>
        <string>8089</string>
        <key>AZURE_KEY_VAULT_NAME</key>
        <string>arca-mcp-kv-dae</string>
        <key>AZURE_TENANT_ID</key>
        <string>{az_tenant}</string>
        <key>AZURE_CLIENT_ID</key>
        <string>{az_client}</string>
    </dict>
    
    <key>RunAtLoad</key>
    <true/>
    
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    
    <key>StandardOutPath</key>
    <string>/Users/danexall/biomimetics/logs/credentials_server.log</string>
    
    <key>StandardErrorPath</key>
    <string>/Users/danexall/biomimetics/logs/credentials_server.err</string>
    
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>"""

    with open(PLIST_PATH, "w") as f:
        f.write(plist_content)
    print(f"✓ LaunchAgent: {PLIST_PATH}")

    print("\n=== Creating Environment File ===")
    env_file = SCRIPT_DIR / ".env"
    with open(env_file, "w") as f:
        f.write(f"""# Azure Credentials Server Configuration
# Generated by setup_credentials_server.py

CREDENTIALS_API_KEY={API_KEY}
CREDENTIALS_PORT=8089
AZURE_KEY_VAULT_NAME=arca-mcp-kv-dae
AZURE_TENANT_ID={az_tenant}
AZURE_CLIENT_ID={az_client}

# Fetch these from Azure Key Vault:
# AZURE_CLIENT_SECRET - Service principal secret (NOT the name, the actual secret value)
# Or use: az account get-access-token --resource https://vault.azure.net to get a token
""")
    print(f"✓ Env file: {env_file}")

    print("\n" + "=" * 60)
    print("SETUP COMPLETE")
    print("=" * 60)
    print(f"""
Next steps:

1. Get Azure client secret (if not already):
   az keyvault secret show --vault-name arca-mcp-kv-dae \\
     --name {az_secret_name} --query value -o tsv

2. Set AZURE_CLIENT_SECRET in your shell:
   export AZURE_CLIENT_SECRET='<secret-value>'

3. Load and start the LaunchAgent:
   launchctl load {PLIST_PATH}

4. Test the server:
   curl -H "X-API-Key: {API_KEY}" http://127.0.0.1:8089/health

5. Add to your shell profile (~/.zshrc):
   echo "export CREDENTIALS_API_KEY='{API_KEY}'" >> ~/.zshrc
   echo "export AZURE_CLIENT_SECRET='<secret-value>'" >> ~/.zshrc

6. Update other services to use:
   - CoPaw MCP config
   - Jarvis daemon
   - Cloudflare Worker (for local development)
""")

    print("\nTo start NOW without LaunchAgent:")
    print(f"  source {env_file} && python {CREDENTIALS_SERVER}")


if __name__ == "__main__":
    main()
